# Generated by Django 2.1.5 on 2019-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('performer', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('filename', models.CharField(max_length=50)),
                ('filetype', models.CharField(max_length=5)),
                ('view_count', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
