# Generated by Django 2.1.5 on 2019-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
