# Generated by Django 2.1.5 on 2019-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoManagement', '0003_auto_20190419_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='view_count',
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='real_id',
            field=models.CharField(default='Enter ID here', max_length=15),
        ),
    ]
